# Generated by Django 5.2.8 on 2026-06-06 11:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('business_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('partial_failed', 'Partial failed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('source_type', models.CharField(default='daily_off_query', max_length=64)),
                ('input_count', models.PositiveIntegerField(default=0)),
                ('fetched_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-business_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basalam_product_id', models.BigIntegerField(db_index=True, unique=True)),
                ('latest_title', models.CharField(blank=True, max_length=255)),
                ('latest_price', models.BigIntegerField(default=0)),
                ('latest_primary_price', models.BigIntegerField(default=0)),
                ('latest_photo_url', models.URLField(blank=True, max_length=700)),
                ('latest_vendor_identifier', models.CharField(blank=True, max_length=160)),
                ('latest_product_url', models.URLField(blank=True, max_length=700)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyProductSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_product_id', models.BigIntegerField(db_index=True)),
                ('business_date', models.DateField(db_index=True)),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('price', models.BigIntegerField(default=0)),
                ('primary_price', models.BigIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True, max_length=700)),
                ('product_status', models.CharField(blank=True, max_length=128)),
                ('inventory', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=False)),
                ('is_saleable', models.BooleanField(default=False)),
                ('is_showable', models.BooleanField(default=False)),
                ('is_wholesale', models.BooleanField(default=False)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('preparation_day', models.PositiveIntegerField(default=0)),
                ('net_weight', models.FloatField(default=0)),
                ('packaged_weight', models.FloatField(default=0)),
                ('unit_quantity', models.FloatField(default=0)),
                ('unit_type', models.CharField(blank=True, max_length=128)),
                ('weight_text', models.CharField(blank=True, max_length=255)),
                ('category_title', models.CharField(blank=True, max_length=255)),
                ('category_parent_title', models.CharField(blank=True, max_length=255)),
                ('navigation_title', models.CharField(blank=True, max_length=255)),
                ('navigation_slug', models.CharField(blank=True, max_length=255)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('vendor_identifier', models.CharField(blank=True, max_length=160)),
                ('vendor_city', models.CharField(blank=True, max_length=255)),
                ('vendor_province', models.CharField(blank=True, max_length=255)),
                ('vendor_status', models.CharField(blank=True, max_length=128)),
                ('attributes_text', models.TextField(blank=True)),
                ('category_list_text', models.TextField(blank=True)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('fetch_status', models.CharField(choices=[('details_fetched', 'Details fetched'), ('fetch_error', 'Fetch error')], db_index=True, default='details_fetched', max_length=32)),
                ('analysis_status', models.CharField(choices=[('analysis_pending', 'Analysis pending'), ('analysis_running', 'Analysis running'), ('analyzed', 'Analyzed'), ('no_match', 'No match'), ('analysis_error', 'Analysis error')], db_index=True, default='analysis_pending', max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='daily_off.dailyrun')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='daily_off.product')),
            ],
            options={
                'ordering': ['-business_date', '-captured_at'],
                'indexes': [models.Index(fields=['product', '-business_date'], name='daily_off_d_product_4df093_idx'), models.Index(fields=['business_date', 'analysis_status'], name='daily_off_d_busines_bee756_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'source_product_id'), name='uniq_daily_snapshot_per_run_product')],
            },
        ),
    ]
