# Generated by Django 5.2.8 on 2026-06-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_off', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproductsnapshot',
            name='details_status',
            field=models.CharField(db_index=True, default='DETAILS_FETCHED', max_length=64),
        ),
        migrations.AddField(
            model_name='dailyproductsnapshot',
            name='status_row',
            field=models.CharField(db_index=True, default='analysis_pending', max_length=64),
        ),
        migrations.AddField(
            model_name='dailyproductsnapshot',
            name='vendor_summary',
            field=models.TextField(blank=True),
        ),
    ]
