# Generated by Django 5.2.8 on 2026-06-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_off', '0002_dailyproductsnapshot_details_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproductsnapshot',
            name='accepted_candidates_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyproductsnapshot',
            name='product_url1',
            field=models.URLField(blank=True, max_length=700),
        ),
        migrations.AddField(
            model_name='dailyproductsnapshot',
            name='product_url2',
            field=models.URLField(blank=True, max_length=700),
        ),
        migrations.AddField(
            model_name='dailyproductsnapshot',
            name='product_url3',
            field=models.URLField(blank=True, max_length=700),
        ),
    ]
