# Generated by Django 5.2.8 on 2026-06-07 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_off', '0004_daily_run_unique_date_and_claim_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, db_index=True, max_length=32)),
                ('to_status', models.CharField(blank=True, db_index=True, max_length=32)),
                ('status_row', models.CharField(blank=True, db_index=True, max_length=64)),
                ('event_type', models.CharField(choices=[('queued', 'Queued'), ('claimed', 'Claimed'), ('started', 'Started'), ('search_started', 'Search started'), ('text_search_completed', 'Text search completed'), ('image_search_completed', 'Image search completed'), ('image_search_skipped', 'Image search skipped'), ('candidates_deduped', 'Candidates deduped'), ('candidates_scored', 'Candidates scored'), ('result_stored', 'Result stored'), ('error', 'Error'), ('requeued', 'Requeued'), ('finished', 'Finished')], db_index=True, max_length=64)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('actor', models.CharField(db_index=True, default='django', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_logs', to='daily_off.product')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_logs', to='daily_off.dailyrun')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_logs', to='daily_off.dailyproductsnapshot')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['snapshot', '-created_at'], name='asl_snapshot_created_idx'), models.Index(fields=['run', '-created_at'], name='asl_run_created_idx'), models.Index(fields=['event_type', '-created_at'], name='asl_event_created_idx')],
            },
        ),
    ]
