# Generated by Django 5.2.8 on 2026-06-09 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_off', '0005_analysisstatuslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('candidate_id', models.BigIntegerField(db_index=True)),
                ('candidate_title', models.CharField(blank=True, max_length=500)),
                ('candidate_price', models.BigIntegerField(default=0)),
                ('candidate_vendor_identifier', models.CharField(blank=True, max_length=160)),
                ('candidate_url', models.URLField(blank=True, max_length=700)),
                ('search_sources', models.JSONField(blank=True, default=list)),
                ('search_text_query', models.CharField(blank=True, max_length=500)),
                ('similarity_score', models.FloatField(default=0)),
                ('embedding_score', models.FloatField(default=0)),
                ('category_score', models.FloatField(default=0)),
                ('unit_score', models.FloatField(default=0)),
                ('source_unit_type', models.CharField(blank=True, max_length=128)),
                ('source_unit_group', models.CharField(blank=True, max_length=32)),
                ('source_quantity_normalized', models.FloatField(blank=True, null=True)),
                ('source_quantity_basis', models.CharField(blank=True, max_length=64)),
                ('candidate_unit_type', models.CharField(blank=True, max_length=128)),
                ('candidate_unit_group', models.CharField(blank=True, max_length=32)),
                ('candidate_quantity_normalized', models.FloatField(blank=True, null=True)),
                ('candidate_quantity_basis', models.CharField(blank=True, max_length=64)),
                ('unit_comparable', models.BooleanField(default=False)),
                ('unit_equivalent', models.BooleanField(default=False)),
                ('title_measurement_used', models.BooleanField(default=False)),
                ('title_measurement_confidence', models.CharField(blank=True, max_length=32)),
                ('source_title_unit', models.CharField(blank=True, max_length=128)),
                ('source_title_quantity_normalized', models.FloatField(blank=True, null=True)),
                ('candidate_title_unit', models.CharField(blank=True, max_length=128)),
                ('candidate_title_quantity_normalized', models.FloatField(blank=True, null=True)),
                ('price_gap', models.BigIntegerField(default=0)),
                ('price_gap_percent', models.FloatField(default=0)),
                ('decision', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, max_length=32)),
                ('rejection_reasons', models.JSONField(blank=True, default=list)),
                ('rejection_reason_text', models.CharField(blank=True, max_length=500)),
                ('raw_candidate', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_candidates', to='daily_off.product')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_candidates', to='daily_off.dailyrun')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_candidates', to='daily_off.dailyproductsnapshot')),
            ],
            options={
                'ordering': ['snapshot_id', '-decision', '-similarity_score', 'candidate_price'],
                'indexes': [models.Index(fields=['snapshot', 'decision'], name='ac_snapshot_decision_idx'), models.Index(fields=['run', 'decision'], name='ac_run_decision_idx'), models.Index(fields=['candidate_id', 'decision'], name='ac_candidate_decision_idx')],
            },
        ),
    ]
