"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure--*t(!#h0dip)oipp&+27vt1n15k@_2ex_1z(*6kumpjp$b_bjv')

def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', default=False)

ALLOWED_HOSTS = [host.strip() for host in os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost,salam-offer.titanapp.dev').split(',') if host.strip()]
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', 'https://salam-offer.titanapp.dev').split(',') if origin.strip()]
CSRF_COOKIE_SECURE = env_bool('DJANGO_CSRF_COOKIE_SECURE', default=not DEBUG)
SESSION_COOKIE_SECURE = env_bool('DJANGO_SESSION_COOKIE_SECURE', default=not DEBUG)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'daily_off.apps.DailyOffConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    parsed_database_url = urlparse(DATABASE_URL)
    database_options = {}
    query_options = parse_qs(parsed_database_url.query)
    if env_bool('DATABASE_SSL_REQUIRE', default=False):
        database_options['sslmode'] = 'require'
    elif query_options.get('sslmode'):
        database_options['sslmode'] = query_options['sslmode'][0]

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': parsed_database_url.path.lstrip('/'),
            'USER': parsed_database_url.username or '',
            'PASSWORD': parsed_database_url.password or '',
            'HOST': parsed_database_url.hostname or '',
            'PORT': parsed_database_url.port or '5432',
            'CONN_MAX_AGE': 600,
            'OPTIONS': database_options,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.getenv('SQLITE_PATH', BASE_DIR / 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

BASALAM_TEXT_SEARCH_URL = os.getenv('BASALAM_TEXT_SEARCH_URL', 'https://services.basalam.com/web/v1/search/product/search')
BASALAM_IMAGE_SEARCH_URL = os.getenv('BASALAM_IMAGE_SEARCH_URL', 'https://services.basalam.com/web/v1/search/image/search')
BASALAM_PRODUCT_DETAIL_URL_TEMPLATE = os.getenv('BASALAM_PRODUCT_DETAIL_URL_TEMPLATE', 'https://openapi.basalam.com/v1/products/{product_id}')
CHEAPER_ANALYSIS_TEXT_SEARCH_SIZE = int(os.getenv('CHEAPER_ANALYSIS_TEXT_SEARCH_SIZE', '20'))
CHEAPER_ANALYSIS_IMAGE_SEARCH_SIZE = int(os.getenv('CHEAPER_ANALYSIS_IMAGE_SEARCH_SIZE', '20'))
CHEAPER_ANALYSIS_DETAIL_FETCH_LIMIT = int(os.getenv('CHEAPER_ANALYSIS_DETAIL_FETCH_LIMIT', '40'))
CHEAPER_ANALYSIS_MIN_SIMILARITY = float(os.getenv('CHEAPER_ANALYSIS_MIN_SIMILARITY', '0.60'))
CHEAPER_ANALYSIS_MIN_CHEAPER_DELTA = int(os.getenv('CHEAPER_ANALYSIS_MIN_CHEAPER_DELTA', '1'))
CHEAPER_ANALYSIS_REQUEST_TIMEOUT_SECONDS = float(os.getenv('CHEAPER_ANALYSIS_REQUEST_TIMEOUT_SECONDS', '15'))
CHEAPER_ANALYSIS_MAX_BATCH_SIZE = int(os.getenv('CHEAPER_ANALYSIS_MAX_BATCH_SIZE', '3'))
CHEAPER_ANALYSIS_STALE_MINUTES = int(os.getenv('CHEAPER_ANALYSIS_STALE_MINUTES', '30'))
CHEAPER_ANALYSIS_ENABLE_IMAGE_SEARCH = env_bool('CHEAPER_ANALYSIS_ENABLE_IMAGE_SEARCH', default=True)
CHEAPER_ANALYSIS_SCORE_WEIGHTS = {
    'embedding': float(os.getenv('CHEAPER_ANALYSIS_WEIGHT_EMBEDDING', '0.65')),
    'category': float(os.getenv('CHEAPER_ANALYSIS_WEIGHT_CATEGORY', '0.20')),
    'weight': float(os.getenv('CHEAPER_ANALYSIS_WEIGHT_WEIGHT', '0.15')),
}

LOG_LEVEL = os.getenv('DJANGO_LOG_LEVEL', 'INFO')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'daily_off': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}
